id: A112EF814
title: Aspiration for the Country’s Welfare
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:23:16.687074
  last_modified_at: 2022-03-01 06:23:16.687078
