id: A112EF814
title: Prayer for Dispelling Famine
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:23:16.688196
  last_modified_at: 2022-03-01 06:23:16.688198
